spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue_mate
    username: ENC(${DB_USER_ENC})
    password: ENC(${DB_PW_ENC})
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

#api_url: http://localhost:8080
next_public_base_url: http://localhost:3000

##kakao login
kakao:
  client:
    id: ${KAKAO_RESTAPIKEY}
  redirect:
    uri: ${KAKAO_REDIRECTURI}