spring:
  profiles:
    active: local

  jwt:
    secretkey: ${JWT_SECRETKEY}

logging:
  level:
    org.hibernate.SQL: info
#    org.hibernate.type: trace
#    org.springframework.security: info

jasypt:
  encryptor:
    password: ${SECRETKEY}
    bean: jasyptStringEncryptor