spring:
  datasource:
    url: jdbc:mysql://localhost:3306/issue_mate
    username: ENC(${DB_USER_ENC})
    password: ENC(${DB_PW_ENC})
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000         # 클라이언트가 SMTP 서버와의 연결을 설정하는데 대기해야하는 시간
          timeout: 5000                   # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          writetimeout: 5000              # 클라이언트가 작업을 완료하는대 대기해야 하는 시간
    auth-code-expiration-millis: 1800000  # 이메일 인증코드의 만료 시간 ( 30 * 60 * 1000 )

#api_url: http://localhost:8080
next_public_base_url: http://localhost:3000

##kakao login
kakao:
  client:
    id: ${KAKAO_RESTAPIKEY}
  redirect:
    uri: ${KAKAO_REDIRECTURI}

coolsms:
  api-key: ${COOLSMS_API_KEY}
  api-secret: ${COOLSMS_API_SECRET}
  sender: "010-9205-9228"